

spring:
  web:
    resources:
      static-locations: file:${user.home}/upload/
  mvc:
    static-path-pattern: /**
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  datasource:
    url: jdbc:mysql://localhost:3306/db_rainbow?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:your_redis_password}
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  security:
    user:
      name: admin
      password: none
      roles: ADMIN
  freemarker:
    settings:
      recognize_standard_file_extensions: true

jwt:
  secret: ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890ABCDEFGH

logging:
  operation:
    enabled: false

# Swagger UI 配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    filter: true
    doc-expansion: none

