server:
  port: 8080
  servlet:
    context-path: /api
    multipart:
      # 单个文件大小
      max-file-size: 200MB
      # 设置总上传的文件大小
      max-request-size: 200MB
project:
  version: 1.0.0


spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  config:
    use-legacy-processing: false
  application:
    name: rainbow-system
  profiles:
    active: dev
  security:
    user:
      name: admin
      password: none
      roles: ADMIN
  freemarker:
    settings:
      recognize_standard_file_extensions: true




